# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MonefyFileSelect(object):
    def setupUi(self, MonefyFileSelect):
        MonefyFileSelect.setObjectName("MonefyFileSelect")
        MonefyFileSelect.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(MonefyFileSelect)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 301))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileTextEdit.sizePolicy().hasHeightForWidth())
        self.fileTextEdit.setSizePolicy(sizePolicy)
        self.fileTextEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.fileTextEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.fileTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fileTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fileTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.fileTextEdit.setObjectName("fileTextEdit")
        self.horizontalLayout.addWidget(self.fileTextEdit)
        self.browseButton = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout.addWidget(self.browseButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.exportButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.exportButton.setObjectName("exportButton")
        self.verticalLayout.addWidget(self.exportButton)
        self.actionexportFile = QtWidgets.QAction(MonefyFileSelect)
        self.actionexportFile.setObjectName("actionexportFile")
        self.actionbrowseFile = QtWidgets.QAction(MonefyFileSelect)
        self.actionbrowseFile.setObjectName("actionbrowseFile")

        self.retranslateUi(MonefyFileSelect)
        self.exportButton.clicked.connect(self.actionexportFile.trigger) # type: ignore
        self.browseButton.clicked.connect(self.actionbrowseFile.trigger) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MonefyFileSelect)

    def retranslateUi(self, MonefyFileSelect):
        _translate = QtCore.QCoreApplication.translate
        MonefyFileSelect.setWindowTitle(_translate("MonefyFileSelect", "Form"))
        self.fileTextEdit.setPlaceholderText(_translate("MonefyFileSelect", "Add File to Import"))
        self.browseButton.setText(_translate("MonefyFileSelect", "..."))
        self.exportButton.setText(_translate("MonefyFileSelect", "Export"))
        self.actionexportFile.setText(_translate("MonefyFileSelect", "exportFile"))
        self.actionbrowseFile.setText(_translate("MonefyFileSelect", "browseFile"))
